### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by sonyccd** [nrandecker/particle#2]
When I try and run gulp I am getting this error.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by sonyccd** [comment]
nvm fixed it with a clean install

**Comment by edgartaor** [comment]
I'm having this problem. Can you explain what you mean with "clean install"?
clean "npm install"?

**Comment by angelfretz23** [comment]
@edgartaor This is how i solved this issue:
```
brew install rbenv ruby-build

# Add rbenv to bash so that it loads every time you open a terminal
echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile
source ~/.bash_profile

# Install Ruby
rbenv install 2.5.1
rbenv global 2.5.1
ruby -v

#Install Jekyll
gem install jekyll

#Restart Terminal and run gulp once again in the project's root directory
```
